version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test

jobs:
  test:
    docker:
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd Backend && npm install
      - run:
          name: Run Tests
          command: cd Backend && npm run test

  deploy:
    docker:
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - run:
          name: Install Render CLI
          command: |
            curl -O https://render.com/download/linux/renderctl
            chmod +x renderctl
            sudo mv renderctl /usr/local/bin
      - run:
          name: Verify Render CLI Installation
          command: renderctl version
      - run:
          name: Deploy to Render
          command: |
            renderctl --file ../Backend/render.yaml --api-key rnd_kO4hNk04ZZOJ8dDCewMnfUgv5JAL up --force
