version: 2.1

workflows:
  test-endpoints:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - run: node --version
          name: Install dependencies
          command: cd Backend && npm install
      - run: 
          name: Run Tests
          command: cd Backend && npm run test    
