version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd Backend && npm install
      - run:
          name: Build
          command: cd Backend && npm run build

  deploy:
    docker:
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - run:
          name: Deploy to Render
          command: |
            curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer rnd_eWSkUvQpjWDBONXu2C3xbPE59eau" -d '{"branch":"main"}' https://api.render.com/v1/deploys

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
