version: 2.1

workflows:
  version: 2
  build-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd Backend && npm install
      - run:
          name: Run Tests
          command: cd Backend && npm run test
